apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: scrapychat-auth-pvc
  annotations:
    argocd.argoproj.io/sync-options: Prune=false

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '2Gi'
