apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
stringData:
  ADMIN_TOKEN: $argon2id$v=19$m=65540,t=3,p=4$1u641IrwKeBzgDOtKdBbHJIenvvLO2icMOaILw+Z3zg$mBbCIx3tBkMaIjKR9qOqrfzKFhIuSl/1ISTmTBD+Ku4
type: Opaque
