apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgB+2z7TkO4c+nhtHSBfu8i0RwRNmCflhGnyu46/qPA7hR9Pwty/EbjGGs08oybC/Gdx2fdxuCJxkYonZPYYdt45Xi8Ic8xhln1E+KNIcm8wTQfvrgUdB9KI7xL2mTpQ4/QD+Vk4T9TGtITE2QGCbRKogI7O6MsMMTayrR196vev1+5eHVGWnnTtcwo92gFJa8gvMtabMZAwgtfZcBX+yK5LjOh5HoB1FdtH+58XcT0jtqs1rwfWHBKmx4GuZojYo2Vcoi7LVDDI+7YU1lCQbXYnwdUi+hhtH7XYJzdL+TnfgaS8osUVsColbfL/d2u3DHHJpR0ElvfSH0z16zJl6G6o5kCOhRwOp8D63CHRRr/LpxiAPktaUyXwaEfZHXuxhWgBVLpnu8OCw4rN1ji3dXA92EPiL9l0AudsIRy5PIhgTZJFs5+gwgeD4T0CdKYeirP5DWe/e66uqimOBPBMsRWytHQeHHOPNrP0kR/5k5PP+d32Pcc569jY/+x8wPIIoApP1RLJOY+mSBrG+yf86dC4AZomDe6HorIvKUb2MGk3ENxQVJXmkEckW/WhveadpALKGyO6oq0lQRgNi9hsFpxEP5JSZsgSHsNB0Ni4q5KDprzVqoQhIT9kuHIKzqThlKnR4TBjKB5qmo63WQvTL3mfBWVd8X8slzlesOQX6uoL7EcogKP8xP50eJKTc87rvnC1L8d7RZMTzsfuhlShf7SyXw==
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
    type: Opaque
