apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secret_key: AgCPM+y2N4X/s3baGVOMAvYPDg5lrBcHX2w0refALavDGi9+3pdK6EAPIReE/hNWsrApzUht2L0mY+WOJlOp4I6eov8yiDMdYRwveQKYSSGSTFSCOBRIXs6pSII1dsHalf8Nd81rBRQDDRbdYnzttvXgI7fJcKdw0qJQs/mKhtiheg2eRyXmiszbHXoe12T7/vBrDjyXv8IP9JivujAgMdCamqWRIaFPZmPvTAv6I0zcmEe99n6OJOJcqVNFzAF+OL/DBC1Rjj7X9KGNk3G9gGyCBFAGdwqkyaqEpUwew1rtM4uib6dhO21u8EZG1Fw0XEJiTUhbzHCChPZagRgq98WUwgb2dQ/Oui9O/A98H1JMoJuGD8Vb+X2Y2j88WBujhxlhw84ur8PKExRPE376uFwuMMGMuJQd1bYyn7jEa9UAK1UIEDgYOkHr9X6nhfasuvkFvbyo9KZ/TiTQqCQBzTlboqAlH63nJcGTTPWhqg1eCVUXyD722mquu+gicse+Pio2NwuXx7khD/CLQ0o/K1C8dUl4Z6lcVgxpkoCtFDxamSWnoNoIelhVJDXH6de6nVaMXdCqOsIGw/nmKcv88yum4nJZE7QYG5Y8p5Ys2mjfKtBg4K3Gm1GidQ+BruROF/Vdja2wqU9yiLWkAdEZbsLAqC7v6Zj/w8hxjeYhdmNGQtQ/+hScqLPALMGm9X/G8MPz8gWf1Ye00J9IlLpRAfegpCS3PRC0wkC/chdsIfB1tLZmXH3xe2AT9t4zJPWPOpU=
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
