apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: ghcr-secret
  namespace: portfolio-prod

spec:
  encryptedData:
    .dockerconfigjson: AgAhTZIhN88TJM67tgAjKqXCBkg08b+szP1cRWC4BepghA/ojfQLj8etEz+yaB44/uhc6wwycRE8kWQd2dXuRWrgjMOH/56DLQ5h0C5iEV1xpuP4XFk36mzRaLuuIyc1RbQiuC2Bp92t6pbefANIyNHyZamdg2NGK0/MP4nfevpj7zjMsZpDJInDvK5SSY0KvYhU8XwAy14z4SGQejsg6gQfnxbElN74XIgI6LduQO3swlr4goMAj9D8+ow51N0ZY0i+aTzNqyAK0dCsMLcTKAron4H2vv6overqx4YZXjfsyqj4l0jTIOulmffBQBf8s5qAbPhyacPuyvKcKnH256vLCYU6wMimkRU6x+gL2fsVYSfCmTuaaQwKxk08XAO955j4bnyYAwhIfpIGDaLcxDvORismsToQAWdMGUJ7XTRzPzNjRXeiLdRUEGCF/7ydZ3adT18tetu/QsmFvAPHBICpZ7HWyUoMP9umMsZuqfy8zEg3Wmwr07gRc2ofK7C2llPVuLU9Z7LeiFeEKz1PQoUYCjIc5OnIZw6EEzoRyFJNro4l9iYgchcIhwsjFMHYGw9iKbYu+Tb/bcEQiuotQTmxYiQw/llEwDWLNNRma6blSC4Puqg2347nzDVPgav9HYLDhyPzd7EVkaYfVaJR6VaI0NxmVoH/V6DildaAkvx7D/IhUqahpqsTPN+Q1aAJbNaJrjZBdl+HRh7Qg7h4l+Oj8bHDIkeZQe3Pd/t5D3rIwbpWho9JWtwvsdL2oZxPpa7vBjfaX4P4wOyHjAoJkZaKTifo4p+9bAnSd6iisRTIDpfm/RC2nb+He9J7mqHDSy6nRhFgv7sWBMc8p66MfIOTXJAIS+3K7k3Ej4pppG7ZiFgj3aLhf7rU1rpwNNequEnIuxTXFTHZdVjkgILX1eOOn4y48QmztreAvRNji6MNMpBQrhvXl+OP
  template:
    metadata:
      name: ghcr-secret
      namespace: portfolio-prod
    type: kubernetes.io/dockerconfigjson
