apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # addons
  - add-ons/cert-manager.yaml
  - add-ons/kyverno.yaml
  - add-ons/sealed-secrets.yaml
  - add-ons/traefik.yaml
  - add-ons/cnpg.yaml
  # services
  - services/app-scrapychat.yaml
  - services/app-gitea.yaml
  - services/app-change-detection.yaml
