apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # addons
  - add-ons/cert-manager.yaml
  - add-ons/sealed-secrets.yaml
  - add-ons/headlamp.yaml
  - add-ons/traefik.yaml

  # services
  ## since only env/prod is used for now.
  - services/app-portfolio.yaml
  - services/app-monitoring.yaml
  - services/app-scrapychat.yaml
