---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCP3T0pNoGLTQrgeEAsPahUyiJDH8Hu4LTU8D8y/J9UXEyFshnDQ/jnRS9JFqV/KA0lG5u62LVhNsUX+ujOHqHy8aH9XoBoSJ7eOZiNQcdQR5nNDRfS589rnfPLRC+wyhOzeRFBqUFQ71NTL0SvUTosNgoOnr90sx4H0U4NxC68EC6Z2KlK5gFulTE6k/6Dq3rLF/0Pxy5jgqyWzFUcezVOm0aha954eVYbC2zlPuHcIcDlEdvpJSNNZ7jGFhL3rj91oeEu6hsYTxn/P+7L+tz7X/+Pbu83m4D8exasMC+MHVUSSloAogFT6ks6apeal4PkIjhysYh/mPzId7U/Vutyb/bYHoPI2xlnjHuuod4L6mCjnIviyRXsk6b+Trm1Yz7kt5ac43pxAxtNAHxlG2bM2w+Qy6ERNEaRAp16NE1VZYTpqBwXay40EJsSUU4oP87AvlsaiwUB08efORT5XReHsu+mnFvL65/qNh14sOtZMzP6AFqLmOqY75Gm3fZo0JxBUFLIbNM8jVrZQAOJz54SyOnqdbTZXwpDdjKaSO1bPmA69ltEheQdOMykarilL+3rlFWjIsNFw7tI9X7/N2iO0enP8ruH5umGAyukYskX+FSCWl0F88fVhO9W2V+VkI/0pveJBZxmfAjYEZYP/5jrWZlYd3c6snSkZVmmnF5XEVeNeel1GwonYJ2Vl7nwjaLueRoVdQVRWae6XTCDrSsFK9PDUbpiCPo1+lU2lQNQDiJjoF0Ql7NkiaPGjHSa6dYvSt9BOg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
