---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: temp-cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDZ4aGUAWQaad6ycGOrjj84bHuUa52io7RNQZLUHEaYaGld5QrOgJZ7XX47OsXpRG78jJQfYYX0zGnZwxcIq0+v5RxM0/zQ1iLd26saY2GMhLucPzG2ZLqxMp2PkwPHy7ulZZuZa6yOpGHu6VJC+mqYEhzxMEkYWtPnjHTir93+3h+whh33MfjqzUx+5qsqtmgf4lg7nasTvBBL3hIPrUsSK1yHYfEKgnI8z2X2VsEy0G8DHCtMeau915ocq9xSIiZmZxNswN6UMY4O4gcVCVX6WsvD7cE2rFB9DLRQAvZWc+08pdUPSO4UGP7JpQ9jwer3x1FcnhK3XKwKBWl30ijOHpWJ0sKK8s/dANDuJQ0Iv8F4xj45Yc31ZWSB5MdrCMtqX5d0XsZj4DLgGIKWSWL6Emh2Z2+U1pR45pbqvL92mPykFa/rVPuuVVSuetZyw98zK5uXbtcyqemsNvD4yy2AbY4CGWv8xJ8K/IvxcAmrHM3EmOsogWPkjcSZ8wQxAM6qJszF929s5G0pGCMLqQJnap57uMNSUCrD+zSEkjeQpR05ahNnFfpto+uL//GnmXRDy1nT2c6Og8+gj0ScXhOHBueSjEHn6bub5eeY8Z7mmKGNxhvBardxlvkl2d+xM3Npv2btX3RJAJfJuu0PB6UO5h4Zs1F5duYUKW5tN6GkzUcKgJZ/aQeMxLYuN9RwNQaGH+TBb5ImxFwBH3fRGpdI+ZqsppG9OqpEg7ixd8/iMNLSTemcPXgG5ZZeU6FeiwTvLkwlqg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: temp-cloudflare-api-token
      namespace: cert-manager
