apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-fe
  namespace: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-fe
  template:
    metadata:
      labels:
        app: lms-fe
    spec:
      containers:
        - image: ghcr.io/hridaya2004/lms-fe:8e62c7498efdbf534c05478be9387cc8b67fa236
          name: lms-fe
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
      imagePullSecrets:
        - name: ghcr-secret
