apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-detection
  template:
    metadata:
      labels:
        app: change-detection
    spec:
      containers:
        - name: change-detection
          image: lscr.io/linuxserver/changedetection.io:0.55.7
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: change-detection-cm
          volumeMounts:
            - mountPath: /config
              name: change-detection-pv
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: change-detection-pv
          persistentVolumeClaim:
            claimName: change-detection-pvc
