apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: change-detection-route
spec:
  hostnames:
    - changedetection.hridaya.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: change-detection
          port: 80
          weight: 1
      filters:
        - requestHeaderModifier:
            remove:
              - Origin
          type: RequestHeaderModifier
        - extensionRef:
            group: traefik.io
            kind: Middleware
            name: change-detection-auth
          type: ExtensionRef
      matches:
        - path:
            type: PathPrefix
            value: /socket.io/
    - backendRefs:
        - group: ""
          kind: Service
          name: change-detection
          port: 80
          weight: 1
      filters:
        - extensionRef:
            group: traefik.io
            kind: Middleware
            name: change-detection-auth
          type: ExtensionRef
      matches:
        - path:
            type: PathPrefix
            value: /
