apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      jsonPointers:
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
      kind: HTTPRoute
  project: default
  sources:
    - chart: vaultwarden
      helm:
        values: |
          resourceType: Deployment

          storage:
            data:
              name: vaultwarden-data
              size: 10Gi
              accessMode: ReadWriteOnce

          adminToken:
            existingSecret: vaultwarden-admin-token
            existingSecretKey: ADMIN_TOKEN

          httpRoute:
            enabled: true
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: traefik-gateway
                namespace: traefik
                sectionName: websecure
            hostnames:
              - vaultwarden.hridaya.dev
            path: /
            rules:
              - matches:
                  - path:
                      type: PathPrefix
                      value: /
                backendRefs:
                  - group: ""
                    kind: Service
                    name: vaultwarden
                    port: 80
                    weight: 1
      repoURL: https://guerzon.github.io/vaultwarden
      targetRevision: 0.43.1
    - path: apps/vaultwarden
      repoURL: https://github.com/hridaya2004/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
