apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: change-detection
  namespace: argocd
spec:
  destination:
    namespace: change-detection
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: apps/change-detection
      repoURL: https://github.com/hridaya2004/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
