apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://github.com/hridaya2004/gitops.git
      targetRevision: main
      path: apps/monitoring/
    - repoURL: https://github.com/kubernetes/kube-state-metrics.git
      targetRevision: release-2.19
      path: examples/standard

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
