apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: gitea
      helm:
        values: |
          ingress:
            enabled: false

          valkey-cluster:
            enabled: false
          valkey:
            enabled: true
          postgresql:
            enabled: true
          postgresql-ha:
            enabled: false

          persistence:
            enabled: true
            size: 10Gi

          service:
            ssh:
              type: LoadBalancer
              port: 2222

          gitea:
            config:
              database:
                DB_TYPE: postgres
              indexer:
                ISSUE_INDEXER_TYPE: bleve
                REPO_INDEXER_ENABLED: true
              server:
                DOMAIN: gitea.hridaya.dev
                ROOT_URL: https://gitea.hridaya.dev/
                # SSH_LISTEN_PORT: 2222 rootless default
                SSH_PORT: 2222
                DISABLE_SSH: false
                START_SSH_SERVER: true
              security:
                REVERSE_PROXY_TRUSTED_PROXIES: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
              service:
                DISABLE_REGISTRATION: true
            admin:
              existingSecret: gitea-admin-secret
      repoURL: https://dl.gitea.com/charts
      targetRevision: 12.7.0
    - path: apps/gitea
      repoURL: https://github.com/hridaya2004/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
