apiVersion: v1
kind: ConfigMap

metadata:
  name: alloy-config
  labels:
    app: alloy

data:
  config.alloy: |
    local.file_match "pods" {
        path_targets = [{__path__ = "/var/log/pods/*/*/*.log"}]
    }

    loki.source.file "kubernetes" {
        targets    = local.file_match.pods.targets
        forward_to = [loki.process.add_k8s_labels.receiver]
    }

    loki.process "add_k8s_labels" {
        stage.regex {
            source     = "__path__"
            expression = "/var/log/pods/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[^/]+)/(?P<container_name>[^_]+)/(?P<restart_count>[^.]*)\\.log"
        }

        stage.labels {
            values = {
                namespace      = "namespace",
                pod_name       = "pod_name",
                container_name = "container_name",
                service_name   = "container_name",
            }
        }

        forward_to = [loki.write.loki.receiver]
    }

    loki.write "loki" {
        endpoint {
            url = "http://loki-service.monitoring.svc.cluster.local/loki/api/v1/push"
        }
    }
