apiVersion: v1
kind: ConfigMap

metadata:
  name: alloy-config
  labels:
    app: alloy

data:
  config.alloy: |
    local.file_match "pods" {
        path_targets = [{__path__ = "/var/log/pods/*/*/*.log"}]
    }

    discovery.relabel "pods" {
        targets = local.file_match.pods.targets

        rule {
            source_labels = ["__path__"]
            regex         = "/var/log/pods/([^_]+)_([^_]+)_([^/]+)/([^_]+)/[^.]+\\.log"
            replacement   = "${1}"
            target_label  = "namespace"
        }

        rule {
            source_labels = ["__path__"]
            regex         = "/var/log/pods/([^_]+)_([^_]+)_([^/]+)/([^_]+)/[^.]+\\.log"
            replacement   = "${2}"
            target_label  = "pod_name"
        }

        rule {
            source_labels = ["__path__"]
            regex         = "/var/log/pods/([^_]+)_([^_]+)_([^/]+)/([^_]+)/[^.]+\\.log"
            replacement   = "${4}"
            target_label  = "container_name"
        }

        rule {
            source_labels = ["__path__"]
            regex         = "/var/log/pods/([^_]+)_([^_]+)_([^/]+)/([^_]+)/[^.]+\\.log"
            replacement   = "${4}"
            target_label  = "service_name"
        }
    }

    loki.source.file "kubernetes" {
        targets    = discovery.relabel.pods.output
        forward_to = [loki.write.loki.receiver]
    }

    loki.write "loki" {
        endpoint {
            url = "http://loki-service.monitoring.svc.cluster.local/loki/api/v1/push"
        }
    }
