apiVersion: apps/v1
kind: Deployment

metadata:
  name: loki
  labels:
    app: loki

spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      # keep pvc on control plane (agent nodes have less space)
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: loki
          image: grafana/loki:3.7.2
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9096
              name: grpc
          volumeMounts:
            - mountPath: /etc/loki
              name: config
              readOnly: true
            - mountPath: /tmp/loki
              name: storage
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 2Gi
          startupProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            periodSeconds: 10
            timeoutSeconds: 3
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: storage
          persistentVolumeClaim:
            claimName: loki-pvc
