apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: lms
spec:
  encryptedData:
    .dockerconfigjson: AgCIuz5jtDtDnSDbKS9szXahhn8Co0QrdMjU7t8jF9PIB38idIu3rhWftxCEyVBEwQrZ0QsXAwUhzLyuxrkyEKr2AMOsIs3Kd2VpMGNR/oHhftxP1e2Ogfess234kizDecLqWvRPmsxcDvrdOZxrmDPBPtosJm+Qff9pBKs+hL6wEYAM0WEIzhy8f0USq8QW6SPwiONv024dfV4yh4/qjLJxVrzc0eHy0Nk1Cw8vUC9HN0IjFn5vxDzEPeWW61hf6sQZkBuMSyH42t0kixUnJqhEShKfJVaxyYpUj2otZW6xy8IrLDigvu5uj56hSrJyaRMZ1C+uhJ205kBgsaG6LOUXsL5mjlS/2jeN0T+6KZm28uSGeyblRnW397LULY4whmwQFjFOI1R7GYSp8SCbH0YRIc5wobSIC66CpvU21sryZNEn0mGDaPAW9UPyK0x09Wa64XrrHcyl9tYdSIaWErn5TYsqhsfqtxwkJMhsIwcy6nhiitsVpql6s8QrS6Y1YPPqlJUvXj02sYJCGBKyBUyaTetlvqwwgxhgNEV5ww9jGU5hJmuvULlJ/IpAkS1y1d2zyiqTfWVjMdStwEdYsxQl0W6Uww9MzH8yNbmgpF59E+o0p1160rgwfuqkJenpXUOzLDSUMg+Ydav8oH+Bi2EyEShiyy8zuOv0fmZR/PwZbZ9CZ3eSkA3gJv7lp1iWRJkqW8CYJUpBkJUalCQfxdgaXevzucgjyC9f/OjWmpU3BccFw83KEyEPJK3842JQAqTTQIw95fE/t2YBcBs/6AvZ8a5niS5ka7RSdtCZO6BjGLOLckSZYYkNgQu/RrglsTxo9R/gIatt17pQw866bUkUgThRI0zclMiUABj/JKCTJyJndgf3UNXLRu5ApxNnpMK3LpkP4DT1R4MlmjyEh4yiNoGAqaS/nMUEFTxkOfZUw7Ph8mpTw0b+
  template:
    metadata:
      name: ghcr-secret
      namespace: lms
    type: kubernetes.io/dockerconfigjson
