apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anubis-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: infra/anubis-operator
      repoURL: https://github.com/hridaya2004/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
