apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: traefik
      helm:
        values: |
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          providers:
            kubernetesGateway:
              enabled: true
            kubernetesIngress:
              enabled: false
          gateway:
            enabled: false
          gatewayClass:
            enabled: false
          ingressClass:
            enabled: false
      repoURL: https://traefik.github.io/charts
      targetRevision: v41.0.2
    - path: infra/traefik-gateway
      repoURL: https://github.com/hridaya2004/gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
