apiVersion: v1
kind: ConfigMap

metadata:
  name: tempo-config
  labels:
    app: tempo

data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    metrics_generator:
      ring:
        kvstore:
          store: inmemory
      registry:
        external_labels:
          source: tempo
          cluster: home
      traces_storage:
        path: /tmp/tempo/generator/traces
      storage:
        path: /tmp/tempo/generator
        remote_write:
          - url: http://loki-service.monitoring.svc.cluster.local/api/v1/push
            send_exemplars: true

    compactor:
      compaction:
        block_retention: 48h

    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics, local-blocks]

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
