apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db
spec:
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
      secret:
        name: miniflux-db-credentials
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
