apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
spec:
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Pod
      name: check-resources
      validate:
        message: CPU and memory resource limits are required
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: ?*
  validationFailureAction: Audit
