apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.monitoring.svc.cluster.local
        isDefault: true
        uid: prometheus

      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service.monitoring.svc.cluster.local
        uid: loki

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-service.monitoring.svc.cluster.local
        uid: tempo
