---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: portfolio
spec:
  encryptedData:
    .dockerconfigjson: AgAPWXnkyC5GFeGF8oseL3yXnfUt34luHBXnb36o9Oqa0/btUGn8Ey4hs7hTJNVm/78UIYbb8DUSu/YxlH9tH12Pf39pLIISr53RzHPQp4WRHPXgY9tsNYDHmikQeko004nE8RLdPBPH8CYsVm6g/ttjsEaHSOj1MCxYDQC9JUigZL0akR8SJHuK8te1SnzWr+EdZqYJZOlW3HeXxWScykR2s62sox4AlK3drFAArwQZWJA9tNcWsb1irpUrih/K+7VJh0gxgEg+W0WO/Xo0wHwFXo1jG7mmwofcO44p8LfwckMtvi8n3hMmmOFeGBZ5iXShDRXxAlABEOWSS609s2APtrNbM2WqPqaIsjlCOXw9S7hfANYow3foZL5Dg2JYZOUsDBNbaorCOGHseeRqzLaw+v7aOQrB+avvJeW4DBlTzN58wrngpgJPeNttUFpd8YZ4a+Akxy31FVXh+0NHN0sqvUXMnQbo08wuQlEl0vvhreHR/KSMdRGBDCKWZrwXpVyxvt/A7MWDY1qwhM5pO4CaYx/dT4oYxAtANxqeiWEO8z76S++4H5GtkGk3WnSnETui3oYyB1QovLTnkDsP4/vc5pAQ2quUuE66Ahe6gGadPIEMlWNpH58O46Xt4w/RTjmK4Xf6cGMmL6hduRzQG7M+CgOmxbXS4vCCKMS9amZp3IRkx0rzQlkqHV21Vc4InX3ZLamTqoi36cEQ965VTl0bpsnXxqJruEZnqnzo5+gwXVMmcYIMChw5+0jkod5tkDIEmSpvrhM1yydZs6m0NaNQRXaEWXD2tRFE7lVTPwi4pD8WrBlEXLMn0Pbgg3Vl4nfIxOtbWCZ6htZgfuPvLjaxPmRU133DXH/rHsnPYfBSgGHCw1sb6QXZhqVPJO5VbQrmY3p7eOhV9Npczeh4cOH+e1HtxWod2bIM9QVsh2p3xAGE7Rs1iiMi
  template:
    metadata:
      name: ghcr-secret
      namespace: portfolio
    type: kubernetes.io/dockerconfigjson
