apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: ghcr-secret
  namespace: portfolio

spec:
  encryptedData:
    .dockerconfigjson: AgBF7m8mMyJzN1aAjIJuYRcgWOGdlKzaln6GZfa5XrmyCSlvXYofrNEnUuldjxdx4cEPcOGLIVOnaC18OHoEw0X85Jc6jRQRkAdxFTsFGMKVG2TYmKEk9iaNQPcH4Pdu4lZSNWvzPgaFD4gbFJApI+CnlUtEpq5DBdpA7SXDutlepMSrwPjDOi0tIM26/bhkzIqxjDhf3VAvary9OcB2lKKcGO2lMAIh5QxLQIX4mauxwPjOT4zPUql/hiOrrzWVlctzzZ8up3hziAFyPet6TNOFEPpdQo+n2+7I9hCDPdb3z2zflPlRTo0DddnZluSpY97fCrg1aNOj22kUy0BUXmKAh3dfK3yGweVLpWdzNSa+WljuNEMnqUTmCu7aOLitL/7FHOu5MpZVXja9jIsccrMXZ1jTjbZINgywVkzgVhSTcnjz0D08a43KYOxetDXTZBintdyLJLgSYpCY/ft8j/45pie+FEEuHf2pklmljheG7YdAWCBEwIECloIkOdteDmqEMrWPXc5ZluglPYqka8tOpopsMgTw47OulyuID7k5ysnzoVtUtNbS8MtBVGRnIK0Dkd/5jBcv726d8A3Crj0rPt6j6Sk6n4BQAuQcn3tk+FkaG3WCpNnYLSaAZhh7bzDIYbIrI+NCl7xnNPRuBvPkUMt0wkp71RJB1YZBDPcLdPN+UOMFV/wOPy19oRpRvW787IL5GkNTzlOqCq3Vg+a+25n/051gI+hsXyc4hUO8Roz32oQoQaI1GRm/ev34po1ZP77Tde7l8nRP/DWW/qi3OENsEVpxVLIA2DqaOCJHqCYs//98jVy5Cf97qPI+YXC1Xm3WHGbpnowKd89VXBWpCfXIDC5ptXSl4oGOjo7f1M7UHIb+FJSd+wuQxCTJEwAIkydP8bxyfgLklunSaBxmzoCMYbmlFYF9ORKz54zXoo3pQyEQ3RCK
  template:
    metadata:
      name: ghcr-secret
      namespace: portfolio
    type: kubernetes.io/dockerconfigjson
