apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scrapychat-prod

resources:
  - ../../base
  - httproute.yaml
  - scrapychat-auth-secrets.yaml
  - scrapychat-backend-configmap.yaml
  - scrapychat-otel-configmap.yaml
