apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anubis-key
  namespace: gitea
spec:
  encryptedData:
    ED25519_PRIVATE_KEY_HEX: AgAtkiIT826zpXjjK3e1nKpBBCvzUhAY2zvlA9PMIh7jZ1rUOcyfVkOSLeuEiTFjecPLQ6QIa2MP+nyzFe04FLoNlPzzItCEm2ag1AxQtswJ3YtyNeOw50C0eVL3oCQefM2WboaYFJfoH74VJ8JuYW4V5acK593D5g7HzGirFlkUMUACMQRc4ZqEr9dbRJ9ukB2CuKMoamBiuC3zY0gfXYQJHbwRAbK0jCYGcuYSYsW7440/dlVfISuW7nPl0ypEK9LBQhkOOmWIlEERFhlcVsT5NBZb2KUXUT2dLz4ka3k7V+OyHX+hM53rAjSm+VuHG/2qukJ0bW/4LrWI6ODXFU5E6JB/0wq+GxZhl6khBjjGOLl+uY12mGNZ6rcBiMj1+MiPUXscRCn5nK+0G298I6+dodfQRb0iMTLT0429b/Y2oey/rm6TwopZhAL7J9TrNFSr2g1DDinQV2XioEEU8aou2JKodE7pyfOi/dVMzkgAqF6OPkHP9Ysm6arClFruiavai5meQ6eaat+ax/jogHT116aIIi9t61fd0htzmsdS0GMDZTwtjkcxnFffumwuw0bjyABx3JCig1EHq58T/UYfpxmZZ+nbKniSkVY/YJfMDjO3qQ3by/XCGcSnwntsCCpIuAM/smvLzSEfkxQi70plxW+sJHiyPVKQSpek6wbPM6hAVXzeUR/ACT6Z+Fe5Frh37rB0T7qSJx/eqBY0vSw0IuTxVB2A7De3oszRqDFKNGpW+5/p+9qcGg+nLGIF2erNSDJAU0vdqcaCFfmMx4MU
  template:
    metadata:
      name: anubis-key
      namespace: gitea
