apiVersion: anubis.techaro.dev/v1alpha1
kind: AnubisProxy
metadata:
  name: gitea
  namespace: gitea
spec:
  anubis:
    config: |
      bots:
        - name: block-internal-api
          path_regex: ^/api/internal
          action: DENY
        - name: block-public-api
          path_regex: ^/api/v1
          action: DENY
    envExtra:
      - name: DIFFICULTY
        value: "4"
      - name: SERVE_ROBOTS_TXT
        value: "true"
      - name: OG_PASSTHROUGH
        value: "true"
      - name: OG_EXPIRY_TIME
        value: 24h
      - name: COOKIE_DOMAIN
        value: gitea.hridaya.dev
      - name: REDIRECT_DOMAINS
        value: gitea.hridaya.dev
      - name: COOKIE_PARTITIONED
        value: "true"
      - name: COOKIE_HTTP_ONLY
        value: "true"
      - name: COOKIE_SAME_SITE
        value: Lax
      - name: DIFFICULTY_IN_JWT
        value: "true"
      - name: SLOG_LEVEL
        value: INFO
    image:
      repository: ghcr.io/techarohq/anubis
      tag: v1.26.2
    keys:
      existingSecret: anubis-key
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  gateway:
    enabled: true
    hostnames:
      - gitea.hridaya.dev
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: traefik-gateway
        namespace: traefik
  ingress:
    enabled: false
  networkPolicy:
    enabled: true
  target:
    service:
      name: gitea-http
      port: 3000
